import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Medium.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Medium.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Medium.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Light.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Light.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Light.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Bold.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Bold.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Bold.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Roman.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Roman.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/HelveticaNeue-Roman.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Regular.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Regular.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Regular.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Light.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Light.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Light.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Medium.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Medium.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/GTWalsheimPro-Medium.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/Bulgari-Regular.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/Bulgari-Regular.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/Bulgari-Regular.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/SchnyderL-Bold.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Bold.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Bold.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/SchnyderL-Demi.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Demi.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Demi.ttf"
            as="font"
            crossOrigin=""
          />

        <link
            rel="preload"
            href="/fonts/SchnyderL-Light.woff2"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Light.woff"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/SchnyderL-Light.ttf"
            as="font"
            crossOrigin=""
          />

        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
